name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    
    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        registry-url: 'https://registry.npmjs.org'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Run tests
      run: npm run test:coverage
    
    - name: Build
      run: npm run build
    
    - name: Create GitHub Release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        body: |
          ## Changes in this Release
          
          See [CHANGELOG.md](CHANGELOG.md) for detailed changes.
          
          ## Installation
          
          ```bash
          npm install tam-mcp-server@${{ github.ref_name }}
          ```
          
          ## Docker
          
          ```bash
          docker pull ghcr.io/gvaibhav/tam-mcp-server:${{ github.ref_name }}
          ```
        draft: false
        prerelease: false
    
    - name: Publish to npm
      run: npm publish --access public
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
    
    - name: Build Docker image
      run: |
        docker build -t ghcr.io/gvaibhav/tam-mcp-server:${{ github.ref_name }} .
        docker build -t ghcr.io/gvaibhav/tam-mcp-server:latest .
    
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Push Docker images
      run: |
        docker push ghcr.io/gvaibhav/tam-mcp-server:${{ github.ref_name }}
        docker push ghcr.io/gvaibhav/tam-mcp-server:latest
